apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-dev
resources:
  - ../../base
replicas:
  - name: whoami
    count: 1
images:
  - name: traefik/whoami
    newTag: v1.10.4
configMapGenerator:
  - name: whoami-env
    literals:
      - ENV=dev
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
