apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-stage
resources:
  - ../../base
replicas:
  - name: whoami
    count: 2
images:
  - name: traefik/whoami
    newTag: v1.10.3
configMapGenerator:
  - name: whoami-env
    literals:
      - ENV=stage
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
